/*
 * The MIT License
 *
 * Copyright 2014 sfcook.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package steamgameselector;

import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author sfcook
 */
public class MainWindow extends javax.swing.JFrame {
    
    private SteamUtils sUtils;
    private SteamData sdb;
    private SteamGameSelector gameSelector;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        sUtils=new SteamUtils();
        sdb=new SteamData(sUtils);
        gameSelector=new SteamGameSelector(sdb);
        initComponents();
        update();
    }
    
    private void update()
    {
        updateAccounts();
        updateGames();
    }
    
    private void updateAccounts()
    {
        DefaultListModel listModel=new DefaultListModel();
        
        for(Account account:gameSelector.getAccounts())
        {
            listModel.addElement(account.name);
        }
        
        lstAccounts.setModel(listModel);
    }
    
    private void updateGames()
    {
        DefaultListModel listModel=new DefaultListModel();
        
        for(Game game:gameSelector.getSharedGames())
        {
            listModel.addElement(game.title);
        }
        
        lstGames.setModel(listModel);
        
        if(listModel.isEmpty())
            btnRandomGame.setEnabled(false);
        else
            btnRandomGame.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        panelLeft = new javax.swing.JPanel();
        scrLstGames = new javax.swing.JScrollPane();
        lstGames = new javax.swing.JList();
        btnRandomGame = new javax.swing.JButton();
        btnNonSteam = new javax.swing.JButton();
        panelRight = new javax.swing.JPanel();
        scrLstAccounts = new javax.swing.JScrollPane();
        lstAccounts = new javax.swing.JList();
        btnAddAccount = new javax.swing.JButton();
        btnRemoveAccount = new javax.swing.JButton();
        btnFilters = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SteamGameSelector");

        splitPane.setPreferredSize(new java.awt.Dimension(500, 600));

        panelLeft.setPreferredSize(new java.awt.Dimension(300, 600));

        scrLstGames.setPreferredSize(new java.awt.Dimension(300, 600));

        scrLstGames.setViewportView(lstGames);

        btnRandomGame.setText("Select Random Game");
        btnRandomGame.setMaximumSize(new java.awt.Dimension(100, 23));
        btnRandomGame.setMinimumSize(new java.awt.Dimension(100, 23));
        btnRandomGame.setPreferredSize(new java.awt.Dimension(100, 23));
        btnRandomGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRandomGameMouseClicked(evt);
            }
        });

        btnNonSteam.setText("Add Non-Steam Game");
        btnNonSteam.setEnabled(false);
        btnNonSteam.setMaximumSize(new java.awt.Dimension(100, 23));
        btnNonSteam.setMinimumSize(new java.awt.Dimension(100, 23));
        btnNonSteam.setPreferredSize(new java.awt.Dimension(100, 23));
        btnNonSteam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNonSteamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRandomGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrLstGames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNonSteam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addComponent(scrLstGames, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRandomGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNonSteam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        splitPane.setLeftComponent(panelLeft);

        panelRight.setPreferredSize(new java.awt.Dimension(100, 600));

        scrLstAccounts.setPreferredSize(new java.awt.Dimension(100, 600));

        lstAccounts.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAccountsValueChanged(evt);
            }
        });
        scrLstAccounts.setViewportView(lstAccounts);

        btnAddAccount.setText("Add Account");
        btnAddAccount.setMaximumSize(new java.awt.Dimension(100, 23));
        btnAddAccount.setMinimumSize(new java.awt.Dimension(100, 23));
        btnAddAccount.setPreferredSize(new java.awt.Dimension(100, 23));
        btnAddAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddAccountMouseClicked(evt);
            }
        });

        btnRemoveAccount.setText("Remove Account");
        btnRemoveAccount.setToolTipText("select account to enable");
        btnRemoveAccount.setEnabled(false);
        btnRemoveAccount.setMaximumSize(new java.awt.Dimension(100, 23));
        btnRemoveAccount.setMinimumSize(new java.awt.Dimension(100, 23));
        btnRemoveAccount.setPreferredSize(new java.awt.Dimension(100, 23));
        btnRemoveAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveAccountMouseClicked(evt);
            }
        });

        btnFilters.setText("Filters");
        btnFilters.setPreferredSize(new java.awt.Dimension(100, 23));
        btnFilters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrLstAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(btnAddAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRemoveAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFilters, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRightLayout.createSequentialGroup()
                .addComponent(scrLstAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoveAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        splitPane.setRightComponent(panelRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNonSteamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNonSteamMouseClicked
        NonSteamWindow addPanel=new NonSteamWindow(); //builds contents of a game obj
        JOptionPane.showConfirmDialog(this,addPanel,"Add Game",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        //todo: retrive result and do things
    }//GEN-LAST:event_btnNonSteamMouseClicked

    private void btnAddAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAccountMouseClicked
        String url="";
        String instructions="Enter public url or source from 'All Games' tab.";
        int result;
        
        AddAccountWindow addPanel=new AddAccountWindow();
        addPanel.setInstructions(instructions);
        
        while(url!=null) //netbeans says url is never null, this is a lie
        {
            result = JOptionPane.showConfirmDialog(this,addPanel,"Add Account",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
            
            url = addPanel.getUrl();
            
            if(result!=JOptionPane.OK_OPTION)
                return;
            else if(gameSelector.addAccount(url)>0)
                break;
            else
                addPanel.setInstructions("Input not valid. Enter public url or source from 'All Games' tab.");
            }
        
        update();
    }//GEN-LAST:event_btnAddAccountMouseClicked

    private void btnRandomGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRandomGameMouseClicked
        int index=gameSelector.getRandomGameIndex();
        Game game=gameSelector.getSharedGames().get(index);
        JOptionPane.showMessageDialog(this, game.title);
    }//GEN-LAST:event_btnRandomGameMouseClicked

    private void btnRemoveAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveAccountMouseClicked
        gameSelector.removeAccount(gameSelector.getAccounts().get(lstAccounts.getSelectedIndex()).accountid);
        update();
        btnRemoveAccount.setEnabled(false);
        btnRemoveAccount.setToolTipText("select account to enable");
    }//GEN-LAST:event_btnRemoveAccountMouseClicked

    private void lstAccountsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAccountsValueChanged
        btnRemoveAccount.setEnabled(true);
        btnRemoveAccount.setToolTipText(null);
    }//GEN-LAST:event_lstAccountsValueChanged

    private void btnFiltersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltersMouseClicked
        FilterWindow addPanel=new FilterWindow(gameSelector.getTags());
        int result=JOptionPane.showConfirmDialog(this,addPanel,"Filters",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        if(result==JOptionPane.OK_OPTION)
        {
            gameSelector.setTags(addPanel.getTags());
        }
        update();
    }//GEN-LAST:event_btnFiltersMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAccount;
    private javax.swing.JButton btnFilters;
    private javax.swing.JButton btnNonSteam;
    private javax.swing.JButton btnRandomGame;
    private javax.swing.JButton btnRemoveAccount;
    private javax.swing.JList lstAccounts;
    private javax.swing.JList lstGames;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JScrollPane scrLstAccounts;
    private javax.swing.JScrollPane scrLstGames;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
